/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.votacao;

import conexao.exceptions.ConnectionException;
import conexao.exceptions.SQLStatementException;
import contreller.DAO.GerenciadorEleicao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Eleicao;
import model.exceptions.ValidacaoCandidatoException;
import model.exceptions.ValidarCursoException;
import model.exceptions.ValidarEleicaoException;
import model.exceptions.ValidarEmailException;
import view.Principal;
import view.gerenciamento.tabelaConfig.EleicaoColumnModel;
import view.gerenciamento.tabelaConfig.EleicaoTableModel;

/**
 *
 * @author Aluno
 */
public class FrmGerenciarVotacao extends javax.swing.JFrame {
    private GerenciadorEleicao ge = new GerenciadorEleicao();
    private ArrayList<Eleicao> listaEleicoesAbertas = new ArrayList<>();
    private ArrayList<Eleicao> listaEleicoesFechadas = new ArrayList<>();
    
    /**
     * Creates new form FrmGerenciarVotacao
     */
    public FrmGerenciarVotacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            EleicaoAbertaTableConfig(definirArrayDeEleicoesAbertas(ge.getTodosEleicoes()));
            EleicaoFechadaTableConfig(definirArrayDeEleicoesFechadas(ge.getTodosEleicoes()));
        } catch (ConnectionException | SQLStatementException | SQLException | ValidacaoCandidatoException | ValidarEleicaoException | ValidarEmailException | ValidarCursoException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tEleicoesAbertas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btIniciarVotacao = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tEleicoesFechadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Votação");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(209, 238, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Iniciar Votação", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        tEleicoesAbertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Eleição", "Data Inicial", "Data Final", "Situação"
            }
        ));
        tEleicoesAbertas.setEnabled(false);
        jScrollPane2.setViewportView(tEleicoesAbertas);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btIniciarVotacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIniciarVotacao.setForeground(new java.awt.Color(0, 102, 0));
        btIniciarVotacao.setText("Iniciar Votação");
        btIniciarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarVotacaoActionPerformed(evt);
            }
        });
        jPanel3.add(btIniciarVotacao);

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Iniciar Votação", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), "Votações Encerradas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        tEleicoesFechadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Eleição", "Data Inicial", "Data Final", "Situação"
            }
        ));
        tEleicoesFechadas.setEnabled(false);
        jScrollPane3.setViewportView(tEleicoesFechadas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Votações Encerradas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btIniciarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarVotacaoActionPerformed
        
            FrmIdentificacao fi = new  FrmIdentificacao();
            fi.setVisible(true);
       
    }//GEN-LAST:event_btIniciarVotacaoActionPerformed

   private void EleicaoAbertaTableConfig(ArrayList<Eleicao> list) {
        setEleicaoAbertaDataList(list);
        tEleicoesAbertas.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = tEleicoesAbertas.getFontMetrics(tEleicoesAbertas.getFont());
        tEleicoesAbertas.setColumnModel(new EleicaoColumnModel(fm));
        tEleicoesAbertas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
   
   private void EleicaoFechadaTableConfig(ArrayList<Eleicao> list) {
        setEleicaoFechadaDataList(list);
        tEleicoesFechadas.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = tEleicoesFechadas.getFontMetrics(tEleicoesFechadas.getFont());
        tEleicoesFechadas.setColumnModel(new EleicaoColumnModel(fm));
        tEleicoesFechadas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public static void setEleicaoAbertaDataList(java.util.List<Eleicao> list) {
        tEleicoesAbertas.setModel(new EleicaoTableModel(list));
    }
    
    public static void setEleicaoFechadaDataList(java.util.List<Eleicao> list) {
        tEleicoesFechadas.setModel(new EleicaoTableModel(list));
    }
    
    private ArrayList<Eleicao> definirArrayDeEleicoesAbertas(ArrayList<Eleicao> lista){
        for(Eleicao e : lista){
            if(e.isSituacao()){
                listaEleicoesAbertas.add(e);
            }
        }
        return listaEleicoesAbertas;
    }
    
    private ArrayList<Eleicao> definirArrayDeEleicoesFechadas(ArrayList<Eleicao> lista){
        for(Eleicao e : lista){
            if(!e.isSituacao()){
                listaEleicoesFechadas.add(e);
            }
        }
        return listaEleicoesFechadas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btIniciarVotacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable tEleicoesAbertas;
    private static javax.swing.JTable tEleicoesFechadas;
    // End of variables declaration//GEN-END:variables
}
