/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.votacao;

import conexao.exceptions.ConnectionException;
import conexao.exceptions.SQLStatementException;
import contreller.DAO.GerenciadorCandidato;
import contreller.DAO.GerenciadorEleicao;
import excecaoEleitor.NomeException;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Candidato;
import model.exceptions.ValidacaoCandidatoException;

/**
 *
 * @author Cliente
 */
public class FrmVotarEmCandidato extends javax.swing.JFrame implements ComponentListener {

    private GerenciadorEleicao ge = new GerenciadorEleicao();
    private GerenciadorCandidato gc = new GerenciadorCandidato();
    private Candidato candidato;

    /**
     * Creates new form FrmVotarEmCandidato
     */
    public FrmVotarEmCandidato() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        addComponentListener(this);
        centralizarPanel(jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftfNumeroCandidato = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbBranco = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbCorrigir = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();

        jButton8.setText("jButton8");

        jButton11.setText("jButton11");

        jButton17.setText("jButton17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), "Escolha um candidato:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 24), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Número do Candidato:");

        ftfNumeroCandidato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));
        ftfNumeroCandidato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        ftfNumeroCandidato.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jb7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb7.setText("7");
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.weightx = 0.3;
        jPanel3.add(jb7, gridBagConstraints);

        jb8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb8.setText("8");
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel3.add(jb8, gridBagConstraints);

        jb9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb9.setText("9");
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 34;
        jPanel3.add(jb9, gridBagConstraints);

        jb4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb4.setText("4");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jb4, gridBagConstraints);

        jb5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb5.setText("5");
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel3.add(jb5, gridBagConstraints);

        jb6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb6.setText("6");
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jb6, gridBagConstraints);

        jb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb1.setText("1");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jb1, gridBagConstraints);

        jb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb2.setText("2");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel3.add(jb2, gridBagConstraints);

        jb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb3.setText("3");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel3.add(jb3, gridBagConstraints);

        jb0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb0.setText("0");
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jb0, gridBagConstraints);

        jbBranco.setBackground(new java.awt.Color(255, 255, 255));
        jbBranco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbBranco.setForeground(new java.awt.Color(102, 102, 102));
        jbBranco.setText("Branco");
        jbBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBrancoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jbBranco, gridBagConstraints);

        jbCancelar.setBackground(new java.awt.Color(255, 0, 0));
        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jbCancelar, gridBagConstraints);

        jbCorrigir.setBackground(new java.awt.Color(255, 255, 0));
        jbCorrigir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCorrigir.setText("Corrigir");
        jbCorrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCorrigirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 33;
        jPanel3.add(jbCorrigir, gridBagConstraints);

        jbConfirmar.setBackground(new java.awt.Color(0, 153, 0));
        jbConfirmar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmar.setText("Confirmar");
        jbConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 38;
        jPanel3.add(jbConfirmar, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfNumeroCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ftfNumeroCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "1");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "2");
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "0");
    }//GEN-LAST:event_jb0ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "3");
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "4");
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "5");
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "6");
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "7");
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "8");
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        this.ftfNumeroCandidato.setText(this.ftfNumeroCandidato.getText() + "9");
    }//GEN-LAST:event_jb9ActionPerformed

    private void jbCorrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCorrigirActionPerformed
        this.ftfNumeroCandidato.setText(null);
    }//GEN-LAST:event_jbCorrigirActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        if (this.ftfNumeroCandidato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite um número.", "Atenção", JOptionPane.WARNING_MESSAGE);
            
        } else {
            try {
                candidato = gc.getCandidatoPorNumero(Integer.parseInt(this.ftfNumeroCandidato.getText()));
                if(candidato != null){
                    candidato = ge.getCandidato(candidato.getIdCandidato(), ControleDeVotacao.getEleicaoSelecionada().getId());
                }
                
            } catch (ConnectionException | SQLStatementException | ValidacaoCandidatoException| NomeException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            } 
            ControleDeVotacao.setCandidatoEscolhido(candidato);
            FrmConfirmarVoto fcv = new FrmConfirmarVoto();
            fcv.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBrancoActionPerformed
        int opc = JOptionPane.showConfirmDialog(rootPane, "Realmente deseja votar em BRANCO?", "Voto Branco", JOptionPane.YES_NO_OPTION);
        if (opc == 0) {
            try {
                ge.votarEmBranco(ControleDeVotacao.getEleicaoSelecionada(), ControleDeVotacao.getEleitorIdentificado());
                FrmEscolherEleicao fee = new FrmEscolherEleicao();
                fee.setVisible(true);
                this.dispose();
                ControleDeVotacao.setEleicaoSelecionada(null);
            } catch (ConnectionException | SQLStatementException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbBrancoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        FrmEscolherEleicao fee = new FrmEscolherEleicao();
        fee.setVisible(true);
        this.dispose();
        ControleDeVotacao.setEleicaoSelecionada(null);
    }//GEN-LAST:event_jbCancelarActionPerformed
    private void centralizarPanel(JPanel p) {
        int pontoLargura = ((this.getWidth() / 2) - p.getWidth() / 2) - 2;
        int pontoAltura = ((this.getHeight() / 2) - p.getHeight() / 2) - 30;

        p.setLocation(pontoLargura, pontoAltura);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftfNumeroCandidato;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbBranco;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbCorrigir;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e) {
        centralizarPanel(jPanel1);
    }

    @Override
    public void componentMoved(ComponentEvent e) {

    }

    @Override
    public void componentShown(ComponentEvent e) {

    }

    @Override
    public void componentHidden(ComponentEvent e) {

    }
}
