/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import conexao.Autenticacao;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.net.URL;
import javax.swing.JOptionPane;
import view.armazenamento.DialogArmazenamentoAdministrador;
import view.armazenamento.DialogArmazenamentoCandidato;
import view.armazenamento.DialogArmazenamentoEleitor;
import view.armazenamento.DialogArmazenamentoFiscal;
import view.gerenciamento.FrmGerenciadorEleicao;
import view.relatorios.Relatorio;
import view.votacao.FrmConfirmarVoto;
import view.votacao.FrmEscolherEleicao;
import view.votacao.FrmGerenciarVotacao;

/**
 *
 * @author Bruna Branco
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.definirIconeDoPanel();
        this.lbUsuario.setText(Autenticacao.getAdministrador().getUsuario());
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btGerenEleicao = new javax.swing.JButton();
        btRelatorioEleicao = new javax.swing.JButton();
        btGerenciarCandidatos = new javax.swing.JButton();
        btGerenciarEleitores = new javax.swing.JButton();
        btGerenciarFiscal = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btGerenciarContas = new javax.swing.JButton();
        btIniciarVotacao = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miGerenciadorEleicao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        gerenciadorCandidato = new javax.swing.JMenuItem();
        miGerenciadorEleitores = new javax.swing.JMenuItem();
        miGerenciadorFiscal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miRelatorios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miCreditos = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Menu Princípal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        btGerenEleicao.setBackground(new java.awt.Color(204, 204, 204));
        btGerenEleicao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGerenEleicao.setForeground(new java.awt.Color(0, 153, 0));
        btGerenEleicao.setText("Gerenciador de Eleição");
        btGerenEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenEleicaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btGerenEleicao, gridBagConstraints);

        btRelatorioEleicao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRelatorioEleicao.setText("Relatório de Eleições");
        btRelatorioEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioEleicaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btRelatorioEleicao, gridBagConstraints);

        btGerenciarCandidatos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGerenciarCandidatos.setForeground(new java.awt.Color(0, 0, 255));
        btGerenciarCandidatos.setText("Gerenciar Candidatos");
        btGerenciarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarCandidatosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btGerenciarCandidatos, gridBagConstraints);

        btGerenciarEleitores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGerenciarEleitores.setForeground(new java.awt.Color(0, 0, 255));
        btGerenciarEleitores.setText("Gerenciar Eleitores");
        btGerenciarEleitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarEleitoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btGerenciarEleitores, gridBagConstraints);

        btGerenciarFiscal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGerenciarFiscal.setForeground(new java.awt.Color(0, 0, 255));
        btGerenciarFiscal.setText("Gerenciar Fiscais");
        btGerenciarFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarFiscalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btGerenciarFiscal, gridBagConstraints);

        btSair.setBackground(new java.awt.Color(204, 204, 204));
        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setForeground(new java.awt.Color(204, 0, 0));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel2.add(btSair, gridBagConstraints);

        btGerenciarContas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGerenciarContas.setForeground(new java.awt.Color(0, 51, 204));
        btGerenciarContas.setText("Gerenciar Contas");
        btGerenciarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarContasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btGerenciarContas, gridBagConstraints);

        btIniciarVotacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIniciarVotacao.setForeground(new java.awt.Color(0, 153, 51));
        btIniciarVotacao.setText("Iniciar Votação");
        btIniciarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarVotacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 20;
        jPanel2.add(btIniciarVotacao, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SOFTWARE PARA \nGERENCIAMENTO DE ELEIÇÕES");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/g14.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuário: ");

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(0, 153, 0));
        lbUsuario.setText("- - -");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("Opções");

        miSair.setForeground(new java.awt.Color(255, 0, 0));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        jMenu1.add(miSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gerenciadores");

        miGerenciadorEleicao.setText("Gerenciador de Eleição");
        miGerenciadorEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerenciadorEleicaoActionPerformed(evt);
            }
        });
        jMenu2.add(miGerenciadorEleicao);
        jMenu2.add(jSeparator1);

        gerenciadorCandidato.setText("Gerenciador Candidato");
        gerenciadorCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciadorCandidatoActionPerformed(evt);
            }
        });
        jMenu2.add(gerenciadorCandidato);

        miGerenciadorEleitores.setText("Gerenciador Eleitores");
        miGerenciadorEleitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerenciadorEleitoresActionPerformed(evt);
            }
        });
        jMenu2.add(miGerenciadorEleitores);

        miGerenciadorFiscal.setText("Gerenciador Fiscais");
        miGerenciadorFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerenciadorFiscalActionPerformed(evt);
            }
        });
        jMenu2.add(miGerenciadorFiscal);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        miRelatorios.setText("Relatórios de Eleições");
        jMenu3.add(miRelatorios);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Créditos");

        miCreditos.setText("Créditos...");
        miCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreditosActionPerformed(evt);
            }
        });
        jMenu4.add(miCreditos);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerenEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenEleicaoActionPerformed
        FrmGerenciadorEleicao ge = new FrmGerenciadorEleicao();
        ge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btGerenEleicaoActionPerformed

    private void btRelatorioEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioEleicaoActionPerformed
        Relatorio r = new Relatorio();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRelatorioEleicaoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        int opc = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(opc == 0){
            Login l = new Login();
        l.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_btSairActionPerformed

    private void btGerenciarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarCandidatosActionPerformed
        DialogArmazenamentoCandidato dac = new DialogArmazenamentoCandidato(this, rootPaneCheckingEnabled);
        dac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btGerenciarCandidatosActionPerformed

    private void btGerenciarEleitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarEleitoresActionPerformed
        DialogArmazenamentoEleitor dae = new DialogArmazenamentoEleitor(this, rootPaneCheckingEnabled);
        dae.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btGerenciarEleitoresActionPerformed

    private void btGerenciarFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarFiscalActionPerformed
       DialogArmazenamentoFiscal daf = new DialogArmazenamentoFiscal(this, rootPaneCheckingEnabled);
       daf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btGerenciarFiscalActionPerformed

    private void btGerenciarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarContasActionPerformed
        DialogArmazenamentoAdministrador daa = new DialogArmazenamentoAdministrador(this, rootPaneCheckingEnabled);
        daa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btGerenciarContasActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        btSairActionPerformed(evt);
    }//GEN-LAST:event_miSairActionPerformed

    private void miGerenciadorEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerenciadorEleicaoActionPerformed
        btGerenEleicaoActionPerformed(evt);
    }//GEN-LAST:event_miGerenciadorEleicaoActionPerformed

    private void gerenciadorCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciadorCandidatoActionPerformed
        btGerenciarCandidatosActionPerformed(evt);
    }//GEN-LAST:event_gerenciadorCandidatoActionPerformed

    private void miGerenciadorEleitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerenciadorEleitoresActionPerformed
        btGerenciarEleitoresActionPerformed(evt);
    }//GEN-LAST:event_miGerenciadorEleitoresActionPerformed

    private void miGerenciadorFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerenciadorFiscalActionPerformed
        btGerenciarFiscalActionPerformed(evt);
    }//GEN-LAST:event_miGerenciadorFiscalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opc = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(opc == 0){
            Login l = new Login();
        l.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btIniciarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarVotacaoActionPerformed
       FrmGerenciarVotacao fgv = new FrmGerenciarVotacao();
       fgv.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btIniciarVotacaoActionPerformed

    private void miCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreditosActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Desenvolvido por:\n"
               + "Bruna Branco - brancobruna07@gmail.com\n"
               + "Vitor de Souza - vitordesolza@gmail.com", "Créditos", WIDTH);
    }//GEN-LAST:event_miCreditosActionPerformed

    private void definirIconeDoPanel(){
        URL url = this.getClass().getResource("/icones/urnaEletronica.png");
        Image imagem = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagem);
       /* ImageIcon imagem = new ImageIcon("src\\icones\\urnaEletronica.png");
        this.setIconImage(imagem.getImage());*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerenEleicao;
    private javax.swing.JButton btGerenciarCandidatos;
    private javax.swing.JButton btGerenciarContas;
    private javax.swing.JButton btGerenciarEleitores;
    private javax.swing.JButton btGerenciarFiscal;
    private javax.swing.JButton btIniciarVotacao;
    private javax.swing.JButton btRelatorioEleicao;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem gerenciadorCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenuItem miCreditos;
    private javax.swing.JMenuItem miGerenciadorEleicao;
    private javax.swing.JMenuItem miGerenciadorEleitores;
    private javax.swing.JMenuItem miGerenciadorFiscal;
    private javax.swing.JMenuItem miRelatorios;
    private javax.swing.JMenuItem miSair;
    // End of variables declaration//GEN-END:variables
}
