/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cadastros;

import controller.selecao.GerenciadorSelecaoFiscal;
import controller.selecao.GerenciadorSelecaoEleitor;
import controller.selecao.GerenciadorSelecaoCandidato;
import view.selecao.DialogSelecionarCandidato;
import view.selecao.DialogSelecionarEleitor;
import view.selecao.DialogSelecionarFiscal;
import view.armazenamento.tabelaArmazenamentoConfig.CandidatoColumnModel;
import view.armazenamento.tabelaArmazenamentoConfig.CandidatoTableModel;
import view.armazenamento.tabelaArmazenamentoConfig.FiscalColumnModel;
import view.armazenamento.tabelaArmazenamentoConfig.FiscalTableModel;
import view.cadastros.configTabelaEleitor.EleitorPesoVotoColumnModel;
import view.cadastros.configTabelaEleitor.EleitorPesoVotoTableModel;
import view.gerenciamento.FrmGerenciadorEleicao;
import conexao.exceptions.ConnectionException;
import conexao.exceptions.SQLStatementException;
import excecaoEleitor.NomeException;
import contreller.DAO.GerenciadorEleicao;
import excecaoEleitor.MatriculaException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Candidato;
import model.Eleicao;
import model.Eleitor;
import model.Fiscal;
import model.exceptions.ValidacaoCandidatoException;
import model.exceptions.ValidarCursoException;
import model.exceptions.ValidarEleicaoException;
import model.exceptions.ValidarEmailException;

/**
 *
 * @author Aluno
 */
public class DialogCadastroDeEleicao extends javax.swing.JDialog {

    /**
     * Creates new form DialogCadastroDeEleicao
     *
     * @param parent
     * @param modal
     */
    public DialogCadastroDeEleicao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            gsc.removerTodos();
            gse.removerTodos();
            gsf.removerTodos();
        } catch (ConnectionException | SQLStatementException | NomeException ex) {
            JOptionPane.showMessageDialog(parent, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        this.setResizable(false);

    }
    private GerenciadorSelecaoEleitor gse = new GerenciadorSelecaoEleitor();
    private GerenciadorSelecaoCandidato gsc = new GerenciadorSelecaoCandidato();
    private GerenciadorSelecaoFiscal gsf = new GerenciadorSelecaoFiscal();
    private GerenciadorEleicao ge = new GerenciadorEleicao();
    private Eleicao e;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        spHoraInicio = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcHoraInicial = new com.toedter.calendar.JDateChooser();
        dcHoraFinal = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cbTipoEleicao = new javax.swing.JComboBox();
        lbTratarNome = new javax.swing.JLabel();
        lbTratarDataInicial = new javax.swing.JLabel();
        lbTratarDataFinal = new javax.swing.JLabel();
        lbTratarTipoEleicao = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btMaisCandidato = new javax.swing.JButton();
        btRemoverCandidato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCandidato = new javax.swing.JTable();
        lbTratarListaCandidato = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tEleitor = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btMaisEleitor = new javax.swing.JButton();
        btRemoverEleitor = new javax.swing.JButton();
        lbTratarListaEleitor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btConcluido = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tFiscal = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        btMaisFiscal = new javax.swing.JButton();
        btRemoverFiscal = new javax.swing.JButton();
        lbTratarListaFiscal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Eleição");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)), "Cadastro de Eleição", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(506, 500));

        spHoraInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados princípais ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        jLabel1.setText("Nome :");

        jLabel2.setText("Data e Hora Inicio:");

        jLabel5.setText("Data e Hora Final :");

        dcHoraInicial.setDate(new java.util.Date(System.currentTimeMillis()));
        dcHoraInicial.setDateFormatString("dd/MM/yyyy hh:mm:ss aaa");
        dcHoraInicial.setMaxSelectableDate(new java.util.Date(253370775713000L));

        dcHoraFinal.setDate(new java.util.Date(System.currentTimeMillis()));
        dcHoraFinal.setDateFormatString("dd/MM/yyyy hh:mm:ss aaa");
        dcHoraFinal.setMaxSelectableDate(new java.util.Date(253370775713000L));

        jLabel12.setText("Tipo de Eleição :");

        cbTipoEleicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Representante de Colegiado", "Gremio Estudantil", "Representante de Turma", "Reitor", "Sim/Não", "Regente de Turma", "Paraninfo", "Orador da Turma", "Patrono da Turma", "Professor Homenageado", "Juramentista da Turma", "Plebiscito", "Outro", " ", " " }));

        lbTratarNome.setForeground(new java.awt.Color(255, 0, 0));

        lbTratarDataInicial.setForeground(new java.awt.Color(255, 0, 0));

        lbTratarDataFinal.setForeground(new java.awt.Color(255, 0, 0));

        lbTratarTipoEleicao.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout spHoraInicioLayout = new javax.swing.GroupLayout(spHoraInicio);
        spHoraInicio.setLayout(spHoraInicioLayout);
        spHoraInicioLayout.setHorizontalGroup(
            spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spHoraInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spHoraInicioLayout.createSequentialGroup()
                        .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(spHoraInicioLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(lbTratarDataInicial))
                            .addGroup(spHoraInicioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(spHoraInicioLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(spHoraInicioLayout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(lbTratarDataFinal))
                                    .addGroup(spHoraInicioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dcHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(spHoraInicioLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTratarNome)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spHoraInicioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTratarTipoEleicao)
                            .addComponent(cbTipoEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))))
        );
        spHoraInicioLayout.setVerticalGroup(
            spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spHoraInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTratarNome)
                .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spHoraInicioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTratarDataInicial)
                        .addGap(38, 38, 38)
                        .addComponent(lbTratarDataFinal)
                        .addGap(38, 38, 38)
                        .addComponent(lbTratarTipoEleicao))
                    .addGroup(spHoraInicioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(dcHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dcHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(spHoraInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbTipoEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha De Candidato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btMaisCandidato.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btMaisCandidato.setForeground(new java.awt.Color(0, 153, 51));
        btMaisCandidato.setText("+");
        btMaisCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisCandidatoActionPerformed(evt);
            }
        });
        jPanel5.add(btMaisCandidato);

        btRemoverCandidato.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btRemoverCandidato.setForeground(new java.awt.Color(255, 0, 0));
        btRemoverCandidato.setText("-");
        btRemoverCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverCandidatoActionPerformed(evt);
            }
        });
        jPanel5.add(btRemoverCandidato);

        tCandidato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Nome", "Foto"
            }
        ));
        jScrollPane1.setViewportView(tCandidato);

        lbTratarListaCandidato.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbTratarListaCandidato)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lbTratarListaCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha De Eleitor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        tEleitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Curso", "Codigo"
            }
        ));
        jScrollPane2.setViewportView(tEleitor);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        btMaisEleitor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btMaisEleitor.setForeground(new java.awt.Color(0, 153, 51));
        btMaisEleitor.setText("+");
        btMaisEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisEleitorActionPerformed(evt);
            }
        });
        jPanel7.add(btMaisEleitor);

        btRemoverEleitor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btRemoverEleitor.setForeground(new java.awt.Color(255, 0, 0));
        btRemoverEleitor.setText("-");
        btRemoverEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverEleitorActionPerformed(evt);
            }
        });
        jPanel7.add(btRemoverEleitor);

        lbTratarListaEleitor.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbTratarListaEleitor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbTratarListaEleitor)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btConcluido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConcluido.setForeground(new java.awt.Color(0, 153, 51));
        btConcluido.setText("Concluir");
        btConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluidoActionPerformed(evt);
            }
        });
        jPanel2.add(btConcluido);

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btCancelar);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha do Fiscal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        tFiscal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone", "Endereço"
            }
        ));
        jScrollPane3.setViewportView(tFiscal);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        btMaisFiscal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btMaisFiscal.setForeground(new java.awt.Color(0, 153, 51));
        btMaisFiscal.setText("+");
        btMaisFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisFiscalActionPerformed(evt);
            }
        });
        jPanel13.add(btMaisFiscal);

        btRemoverFiscal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btRemoverFiscal.setForeground(new java.awt.Color(255, 0, 0));
        btRemoverFiscal.setText("-");
        btRemoverFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverFiscalActionPerformed(evt);
            }
        });
        jPanel13.add(btRemoverFiscal);

        lbTratarListaFiscal.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(lbTratarListaFiscal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTratarListaFiscal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spHoraInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(194, 194, 194))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMaisCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisCandidatoActionPerformed
        DialogSelecionarCandidato dsc = new DialogSelecionarCandidato(null, rootPaneCheckingEnabled);
        dsc.setVisible(true);
    }//GEN-LAST:event_btMaisCandidatoActionPerformed

    private void btMaisEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisEleitorActionPerformed
        DialogSelecionarEleitor dse = new DialogSelecionarEleitor(null, rootPaneCheckingEnabled);
        dse.setVisible(true);
    }//GEN-LAST:event_btMaisEleitorActionPerformed

    private void btMaisFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisFiscalActionPerformed
        DialogSelecionarFiscal dsf = new DialogSelecionarFiscal(null, rootPaneCheckingEnabled);
        dsf.setVisible(true);
    }//GEN-LAST:event_btMaisFiscalActionPerformed

    private void btConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluidoActionPerformed
        this.getDados();
        try {
            if (tratarListas()) {
                JOptionPane.showMessageDialog(this, "Erro: Existem Listas vazias!", "Erro!", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                if (!verificarElementosIguaisNaMesmaLista()) {
                    ge.salvar(e);
                    gsc.removerTodos();
                    gsf.removerTodos();
                    gse.removerTodos();
                }else{
                    return;
                }
            }

        } catch (ConnectionException | SQLStatementException | SQLException | NomeException | ValidacaoCandidatoException | ValidarEmailException | MatriculaException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        } catch (ValidarEleicaoException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            tratarExcecoes(ex);
        }
        FrmGerenciadorEleicao fge = new FrmGerenciadorEleicao();
        fge.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btConcluidoActionPerformed

    private void btRemoverCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverCandidatoActionPerformed
        try {
            gsc.remover(gsc.getTodosCandidatos().get(DialogCadastroDeEleicao.tCandidato.getSelectedRow()));
            this.CandidatoTableConfig(gsc.getTodosCandidatos());
        } catch (ConnectionException | SQLStatementException | SQLException | ValidacaoCandidatoException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btRemoverCandidatoActionPerformed

    private void btRemoverEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverEleitorActionPerformed
        try {

            gse.remover(gse.obterTodos().get(DialogCadastroDeEleicao.tEleitor.getSelectedRow()));
            DialogCadastroDeEleicao.EleitorTableConfig(gse.obterTodos());
        } catch (SQLStatementException | ConnectionException | NomeException | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btRemoverEleitorActionPerformed

    private void btRemoverFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverFiscalActionPerformed
        try {
            gsf.remover(gsf.obterTodos().get(DialogCadastroDeEleicao.tFiscal.getSelectedRow()));
            this.FiscalTableConfig(gsf.obterTodos());
        } catch (SQLStatementException | ConnectionException | NomeException | SQLException | ValidarEmailException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btRemoverFiscalActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
        try {
            gsc.removerTodos();
            gsf.removerTodos();
            gse.removerTodos();
        } catch (ConnectionException | SQLStatementException | NomeException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        FrmGerenciadorEleicao fge = new FrmGerenciadorEleicao();
        fge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        try {
            gsc.removerTodos();
            gsf.removerTodos();
            gse.removerTodos();
        } catch (ConnectionException | SQLStatementException | NomeException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

        FrmGerenciadorEleicao fge = new FrmGerenciadorEleicao();
        fge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void CandidatoTableConfig(ArrayList<Candidato> list) {
        DialogCadastroDeEleicao.setCandidatoDataList(list);
        DialogCadastroDeEleicao.tCandidato.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = DialogCadastroDeEleicao.tCandidato.getFontMetrics(DialogCadastroDeEleicao.tCandidato.getFont());
        DialogCadastroDeEleicao.tCandidato.setColumnModel(new CandidatoColumnModel(fm));
        DialogCadastroDeEleicao.tCandidato.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DialogCadastroDeEleicao.tCandidato.setRowHeight(150);

    }

    public static void setCandidatoDataList(java.util.List<Candidato> list) {
        DialogCadastroDeEleicao.tCandidato.setModel(new CandidatoTableModel(list));
        DialogCadastroDeEleicao.tCandidato.setRowHeight(150);
    }

    public static void EleitorTableConfig(ArrayList<Eleitor> list) {
        DialogCadastroDeEleicao.setEleitorDataList(list);
        DialogCadastroDeEleicao.tEleitor.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = DialogCadastroDeEleicao.tEleitor.getFontMetrics(DialogCadastroDeEleicao.tEleitor.getFont());
        DialogCadastroDeEleicao.tEleitor.setColumnModel(new EleitorPesoVotoColumnModel(fm));
        DialogCadastroDeEleicao.tEleitor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public static void setEleitorDataList(java.util.List<Eleitor> list) {
        DialogCadastroDeEleicao.tEleitor.setModel(new EleitorPesoVotoTableModel(list));
    }

    private void FiscalTableConfig(ArrayList<Fiscal> list) {
        DialogCadastroDeEleicao.setFiscalDataList(list);
        DialogCadastroDeEleicao.tFiscal.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = DialogCadastroDeEleicao.tFiscal.getFontMetrics(DialogCadastroDeEleicao.tFiscal.getFont());
        DialogCadastroDeEleicao.tFiscal.setColumnModel(new FiscalColumnModel(fm));
        DialogCadastroDeEleicao.tFiscal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public static void setFiscalDataList(java.util.List<Fiscal> list) {
        DialogCadastroDeEleicao.tFiscal.setModel(new FiscalTableModel(list));
    }

    private void getDados() {
        try {
            e = new Eleicao();
            e.setNome(this.tfNome.getText());
            e.setDataHoraFinal(this.dcHoraFinal.getDate().getTime());
            e.setDataHoraInico(this.dcHoraInicial.getDate().getTime());
            e.setTipoEleicao((String) this.cbTipoEleicao.getSelectedItem());
            e.setListaCandidato(gsc.getTodosCandidatos());
            e.setListaEleitor(gse.obterTodos());
            e.setListaFiscal(gsf.obterTodos());
            e.setSituacao(true);
        } catch (ConnectionException | SQLStatementException | SQLException | NomeException | ValidacaoCandidatoException | ValidarEleicaoException | ValidarEmailException | MatriculaException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tratarExcecoes(Exception ex) {
        if (((ValidarEleicaoException) ex).getType() == 0 || ((ValidarEleicaoException) ex).getType() == 1) {
            this.lbTratarNome.setText("Os dados do nome não são válidos!");
            this.tfNome.selectAll();
            this.tfNome.requestFocus();
        } else {
            this.lbTratarNome.setText(null);
        }

        if (((ValidarEleicaoException) ex).getType() == 2) {
            this.lbTratarDataInicial.setText("A data Inicial não pode estar em branco!");
            this.dcHoraInicial.requestFocus();
        } else {
            this.lbTratarDataInicial.setText(null);
        }

        if (((ValidarEleicaoException) ex).getType() == 3) {
            this.lbTratarDataFinal.setText("A data Final não pode estar em branco!");
            this.dcHoraFinal.requestFocus();
        } else {
            this.lbTratarDataFinal.setText(null);
        }

        if (((ValidarEleicaoException) ex).getType() == 4) {
            this.lbTratarDataFinal.setText("A data Final não pode menor que a data Inical");
            this.dcHoraFinal.requestFocus();
        } else {
            this.lbTratarDataFinal.setText(null);
        }

        if (((ValidarEleicaoException) ex).getType() == 5) {
            this.lbTratarTipoEleicao.setText("Não há um tipo de eleição selecionado!");
            this.cbTipoEleicao.requestFocus();
        } else {
            this.lbTratarTipoEleicao.setText(null);
        }
    }

    private boolean tratarListas() throws SQLStatementException, ConnectionException, SQLException, ValidacaoCandidatoException, NomeException, ValidarEmailException, MatriculaException, ValidarCursoException {
        boolean tratamento = false;
        if (gsc.getTodosCandidatos().isEmpty()) {
            tratamento = true;
            this.lbTratarListaCandidato.setText("A lista de Candidatos não pode estar vazia!");
        } else {
            this.lbTratarListaCandidato.setText(null);
        }

        if (gse.obterTodos().isEmpty()) {
            tratamento = true;
            this.lbTratarListaEleitor.setText("A lista de Eleitores não pode estar vazia!");
        } else {
            this.lbTratarListaEleitor.setText(null);
        }

        if (gsf.obterTodos().isEmpty()) {
            tratamento = true;
            this.lbTratarListaFiscal.setText("A lista de Fiscais não pode estar vazia!");
        } else {
            this.lbTratarListaFiscal.setText(null);
        }

        return tratamento;
    }

    private boolean verificarElementosIguaisNaMesmaLista() throws SQLStatementException, ConnectionException, SQLException, ValidacaoCandidatoException, NomeException, ValidarEmailException, MatriculaException, ValidarCursoException {
        boolean existeElementosIguais = false;
        for (Candidato c : gsc.getTodosCandidatos()) {
            if (gsc.getTodosCandidatos(c.getIdCandidato()).size() > 1) {
                existeElementosIguais = true;
                JOptionPane.showMessageDialog(this, "Existem Candidatos iguais na lista de candidatos!", "Atenção!", JOptionPane.WARNING_MESSAGE);
            }
        }

        for (Eleitor e : gse.obterTodos()) {
            if (gse.obterTodos(e.getId()).size() > 1) {
                existeElementosIguais = true;
                JOptionPane.showMessageDialog(this, "Existem Eleitores iguais na lista de eleitores!", "Atenção!", JOptionPane.WARNING_MESSAGE);
            }
        }
        for (Fiscal f : gsf.obterTodos()) {
            if (gsf.obterTodos(f.getId()).size() > 1) {
                existeElementosIguais = true;
                JOptionPane.showMessageDialog(this, "Existem Fiscais iguais na lista de fiscais!", "Atenção!", JOptionPane.WARNING_MESSAGE);
            }
        }
        return existeElementosIguais;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConcluido;
    private javax.swing.JButton btMaisCandidato;
    private javax.swing.JButton btMaisEleitor;
    private javax.swing.JButton btMaisFiscal;
    private javax.swing.JButton btRemoverCandidato;
    private javax.swing.JButton btRemoverEleitor;
    private javax.swing.JButton btRemoverFiscal;
    private javax.swing.JComboBox cbTipoEleicao;
    private com.toedter.calendar.JDateChooser dcHoraFinal;
    private com.toedter.calendar.JDateChooser dcHoraInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbTratarDataFinal;
    private javax.swing.JLabel lbTratarDataInicial;
    private javax.swing.JLabel lbTratarListaCandidato;
    private javax.swing.JLabel lbTratarListaEleitor;
    private javax.swing.JLabel lbTratarListaFiscal;
    private javax.swing.JLabel lbTratarNome;
    private javax.swing.JLabel lbTratarTipoEleicao;
    private javax.swing.JPanel spHoraInicio;
    private static javax.swing.JTable tCandidato;
    private static javax.swing.JTable tEleitor;
    private static javax.swing.JTable tFiscal;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
