/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.armazenamento;

import view.Principal;
import view.armazenamento.tabelaArmazenamentoConfig.EleitorColumnModel;
import view.armazenamento.tabelaArmazenamentoConfig.EleitorTableModel;
import view.cadastros.DialogCadastroEleitor;
import conexao.exceptions.ConnectionException;
import conexao.exceptions.SQLStatementException;
import excecaoEleitor.NomeException;
import contreller.DAO.GerenciadorEleitor;
import excecaoEleitor.MatriculaException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Eleitor;
import model.exceptions.ValidarCursoException;
import model.exceptions.ValidarEmailException;

/**
 *
 * @author Aluno
 */
public class DialogArmazenamentoEleitor extends javax.swing.JDialog {

    private Eleitor eleitor;
    private GerenciadorEleitor ge = new GerenciadorEleitor();

    /**
     * Creates new form DialogArmazenamentoEleitor
     *
     * @param parent
     * @param modal
     */
    public DialogArmazenamentoEleitor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarTabela();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tEleitoresCadastrados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btMaisEleitor = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        bFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfFiltroCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNomeFiltro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eleitores Cadastrado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Eleitores Cadastrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        tEleitoresCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Curso", "Codigo"
            }
        ));
        tEleitoresCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEleitoresCadastradosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tEleitoresCadastrados);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btMaisEleitor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btMaisEleitor.setForeground(new java.awt.Color(0, 102, 0));
        btMaisEleitor.setText("+ Eleitor");
        btMaisEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisEleitorActionPerformed(evt);
            }
        });
        jPanel2.add(btMaisEleitor);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 0, 0));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluir);

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btCancelar);

        bFechar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bFechar.setForeground(new java.awt.Color(0, 0, 204));
        bFechar.setText("Fechar");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });
        jPanel2.add(bFechar);

        jLabel1.setText("Filtros:");

        jLabel2.setText("Curso:");

        tfFiltroCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroCursoKeyReleased(evt);
            }
        });

        jLabel3.setText("Nome:");

        tfNomeFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeFiltroKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfFiltroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tfNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfFiltroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMaisEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisEleitorActionPerformed
        DialogCadastroEleitor dce = new DialogCadastroEleitor(null, rootPaneCheckingEnabled);
        dce.setVisible(true);
    }//GEN-LAST:event_btMaisEleitorActionPerformed

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bFecharActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        try {

            eleitor = new Eleitor();
            eleitor = ge.obterTodos().get(tEleitoresCadastrados.getSelectedRow());
            int opc = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente remover o Eleitor?", "Excluir..", JOptionPane.YES_NO_OPTION);
            if (opc == 0) {
                ge.remover(eleitor);
                configurarTabela();
            }
        } catch (SQLStatementException | ConnectionException | NomeException | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    private void tEleitoresCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEleitoresCadastradosMouseClicked
        if (evt.getClickCount() == 2) {
            DialogCadastroEleitor dce = new DialogCadastroEleitor(null, rootPaneCheckingEnabled);

            try {
                dce.setEleitorInterface(ge.obterTodos().get(tEleitoresCadastrados.getSelectedRow()));
                dce.getTfCurso().setText(dce.getEleitorInterface().getCurso());
                dce.getTfEmail().setText(dce.getEleitorInterface().getEmail());
                dce.getTfMatricula().setText(dce.getEleitorInterface().getMatricula());
                dce.getTfNome().setText(dce.getEleitorInterface().getNome());
                dce.setVisible(true);
            } catch (SQLStatementException | ConnectionException | NomeException | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tEleitoresCadastradosMouseClicked

    private void tfFiltroCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroCursoKeyReleased
        try {
            if (this.tfNomeFiltro.getText().isEmpty()) {
                setListaEleitor(ge.obterTodos(this.tfFiltroCurso.getText()));
            } else {
                setListaEleitor(ge.obterTodosPorNomeECurso(this.tfNomeFiltro.getText(), this.tfFiltroCurso.getText()));
            }

        } catch (SQLStatementException | ConnectionException | NomeException  | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfFiltroCursoKeyReleased

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        try {
            setListaEleitor(ge.obterTodos());
        } catch (SQLStatementException | ConnectionException | NomeException | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfNomeFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeFiltroKeyReleased
        try {
            if (this.tfFiltroCurso.getText().isEmpty()) {
                setListaEleitor(ge.obterTodosPorNome(this.tfNomeFiltro.getText()));
            } else {
                setListaEleitor(ge.obterTodosPorNomeECurso(this.tfNomeFiltro.getText(), this.tfFiltroCurso.getText()));
            }
        } catch (SQLStatementException | ConnectionException | NomeException | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfNomeFiltroKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    public static void setListaEleitor(java.util.List<Eleitor> listaDados) {
        DialogArmazenamentoEleitor.tEleitoresCadastrados.setModel(new EleitorTableModel(listaDados));
    }

    private void configurarTabela() {
        try {
            DialogArmazenamentoEleitor.setListaEleitor(ge.obterTodos());
        } catch (ConnectionException | SQLStatementException | NomeException | MatriculaException | ValidarEmailException | ValidarCursoException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        tEleitoresCadastrados.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = tEleitoresCadastrados.getFontMetrics(tEleitoresCadastrados.getFont());
        tEleitoresCadastrados.setColumnModel(new EleitorColumnModel(fm));
        tEleitoresCadastrados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public Eleitor getEleitorSelecionado() {
        return ((EleitorTableModel) tEleitoresCadastrados.getModel()).getObjetoSelecionado(
                tEleitoresCadastrados.getSelectedRow());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFechar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btMaisEleitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tEleitoresCadastrados;
    private javax.swing.JTextField tfFiltroCurso;
    private javax.swing.JTextField tfNomeFiltro;
    // End of variables declaration//GEN-END:variables
}
