/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.armazenamento;

import view.Principal;
import view.armazenamento.tabelaArmazenamentoConfig.FiscalColumnModel;
import view.armazenamento.tabelaArmazenamentoConfig.FiscalTableModel;
import view.cadastros.DialogCadastroDeFiscal;
import conexao.exceptions.ConnectionException;
import conexao.exceptions.SQLStatementException;
import excecaoEleitor.NomeException;
import contreller.DAO.GerenciadorDeFiscal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Fiscal;
import model.exceptions.ValidarEmailException;

/**
 *
 * @author Aluno
 */
public class DialogArmazenamentoFiscal extends javax.swing.JDialog {

    private Fiscal fiscal;
    private GerenciadorDeFiscal gf = new GerenciadorDeFiscal();

    /**
     * Creates new form DialogArmazenamentoFiscal
     */
    public DialogArmazenamentoFiscal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarTabela();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tFiscaisCadastrados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btMiasFiscal = new javax.swing.JButton();
        btExclauir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfFiltroNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fiscais Cadastrados");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fiscais Cadastrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        tFiscaisCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone", "Endereço"
            }
        ));
        tFiscaisCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFiscaisCadastradosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tFiscaisCadastrados);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btMiasFiscal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btMiasFiscal.setForeground(new java.awt.Color(0, 102, 0));
        btMiasFiscal.setText("+ Fiscal");
        btMiasFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMiasFiscalActionPerformed(evt);
            }
        });
        jPanel2.add(btMiasFiscal);

        btExclauir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExclauir.setForeground(new java.awt.Color(255, 0, 0));
        btExclauir.setText("Excluir");
        btExclauir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExclauirActionPerformed(evt);
            }
        });
        jPanel2.add(btExclauir);

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btCancelar);

        btFechar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFechar.setForeground(new java.awt.Color(0, 0, 204));
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel2.add(btFechar);

        jLabel1.setText("Filtros:");

        jLabel2.setText("Nome:");

        tfFiltroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
        Principal p = new Principal();
        p.setVisible(true);
    }//GEN-LAST:event_btFecharActionPerformed

    private void btMiasFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMiasFiscalActionPerformed
        DialogCadastroDeFiscal dcf = new DialogCadastroDeFiscal(null, rootPaneCheckingEnabled);
        dcf.setVisible(true);
    }//GEN-LAST:event_btMiasFiscalActionPerformed

    private void btExclauirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExclauirActionPerformed

        try {

            fiscal = new Fiscal();
            fiscal = gf.obterTodos().get(tFiscaisCadastrados.getSelectedRow());
            int opc = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente remover o Fiscal?", "Excluir..", JOptionPane.YES_NO_OPTION);
            if (opc == 0) {
                gf.remover(fiscal);
                configurarTabela();
            }
        } catch (SQLStatementException | ConnectionException | NomeException | SQLException | ValidarEmailException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btExclauirActionPerformed

    private void tFiscaisCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFiscaisCadastradosMouseClicked
        if (evt.getClickCount() == 2) {
            DialogCadastroDeFiscal dcf = new DialogCadastroDeFiscal(null, rootPaneCheckingEnabled);
            try {
                dcf.setFiscalInterface(gf.obterTodos().get(tFiscaisCadastrados.getSelectedRow()));
                dcf.getTfEmail().setText(dcf.getFiscalInterface().getEmail());
                dcf.getTfEndereco().setText(dcf.getFiscalInterface().getEndereco());
                dcf.getTfNome().setText(dcf.getFiscalInterface().getNome());
                dcf.getTfTelefone().setText(dcf.getFiscalInterface().getTelefone());
                dcf.setVisible(true);
            } catch (SQLStatementException | ConnectionException | NomeException | SQLException | ValidarEmailException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tFiscaisCadastradosMouseClicked

    private void tfFiltroNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroNomeKeyReleased
        try {
            setListaFiscal(gf.obterTodos(this.tfFiltroNome.getText()));
        } catch (SQLStatementException | ConnectionException | NomeException | SQLException | ValidarEmailException ex) {
           JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfFiltroNomeKeyReleased

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.tfFiltroNome.setText(null);
        try {
            setListaFiscal(gf.obterTodos());
        } catch (SQLStatementException | ConnectionException | NomeException | SQLException | ValidarEmailException ex) {
           JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        Principal p = new Principal();
        p.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public static void setListaFiscal(java.util.List<Fiscal> listaDados) {
        DialogArmazenamentoFiscal.tFiscaisCadastrados.setModel(new FiscalTableModel(listaDados));
    }

    private void configurarTabela() {
        try {
            DialogArmazenamentoFiscal.setListaFiscal(gf.obterTodos());
        } catch (ConnectionException | SQLStatementException | SQLException | NomeException | ValidarEmailException ex) {
            Logger.getLogger(DialogArmazenamentoEleitor.class.getName()).log(Level.SEVERE, null, ex);
        }
        tFiscaisCadastrados.setAutoCreateColumnsFromModel(false);
        java.awt.FontMetrics fm = tFiscaisCadastrados.getFontMetrics(tFiscaisCadastrados.getFont());
        tFiscaisCadastrados.setColumnModel(new FiscalColumnModel(fm));
        tFiscaisCadastrados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public Fiscal getFiscalSelecionado() {
        return ((FiscalTableModel) tFiscaisCadastrados.getModel()).getObjetoSelecionado(
                tFiscaisCadastrados.getSelectedRow());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExclauir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btMiasFiscal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable tFiscaisCadastrados;
    private javax.swing.JTextField tfFiltroNome;
    // End of variables declaration//GEN-END:variables
}
